### ISSUE TITLE
Comparison w/ npm module of the same name?

### ISSUE THREAD

**Issue by NfNitLoop** [y3llowcake/protoc-gen-ts#2]
Oops, I arrived at this page when I was actually searching for the [npm module][1] of the same name. What are the differences between this codebase and that one? Do you plan to publish an npm module?

[1]: https://www.npmjs.com/package/protoc-gen-ts

**Comment by y3llowcake** [comment]
This repository is unmaintained. At the time of development there were some very notable differences some of which are discussed in the README. Unless you plan to fork & own this repo, my recommendation is to use something better maintained.

Cheers
-Cy
